AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ReactAppBucket:
    Type: AWS::S3::Bucket

  ReactAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactAppBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${ReactAppBucket}/*
            Principal: '*'
